---
title: "Hans Martinez's CV"
author: Hans Martinez
date: "`r Sys.Date()`"
params:
  soft1: "Critical thinker"
  soft2: "Grit"
  soft3: "Leadership"
  tech1: "Data Science and Machine Learning"
  tech2: "Econometric Modeling"
  tech3: "Data Visualization"
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---
---
soft1: `r params$soft1`
soft2: `r params$soft2`
soft3: `r params$soft3`
tech1: `r params$tech1`
tech2: `r params$tech2`
tech3: `r params$tech3`
---
```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1JoK4tb-81ruPrv553DzY-JSIKSaCR9TW80i8--qhuqE/edit?usp=sharing",  
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
datadrivencv::build_network_logo(CV$entries_data)
```


```{r}
if(params$pdf_mode){
  cat("View this CV [online](https://raw.githack.com/hans-mtz/DataCV/master/cv.html)")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://hansmartinez.com/uploads/HansCV.pdf)")
  
}
```

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```



Software {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skill_bars()
```

Languages {#langs}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skill_bars(var="langs")
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

<!-- Made with the R package [**pagedown**](https://github.com/rstudio/pagedown). -->

<!-- The source code is available [on github.com/nstrayer/cv](https://github.com/hans-mtz/DataCV). -->

Last updated on `r Sys.Date()`.



Main
================================================================================

Hans Martinez {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```

<!-- > *Enhancing Data Science and Machine Learning with Economics* -->

<!-- |Soft Skills | Technical Skills | -->
<!-- |:-----------|:-----------------| -->
<!-- | `r params$soft1` | `r params$tech1` |  -->
<!-- | `r params$soft2` | `r params$tech2` | -->
<!-- | `r params$soft3` | `r params$tech3` | -->

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```


Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

<!-- ::: aside -->
<!-- ```{r} -->
<!-- CV %<>% print_text_block('teaching_experience_aside') -->
<!-- ``` -->
<!-- ::: -->

```{r}
CV %<>% print_section('teaching_positions')
```

<!-- These breaks just force a new page so section doesnt get cut off -->
<br>
<br>
<br>

Research Experience {data-icon=laptop}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('research_positions')
```



Working Papers {data-icon=file}
--------------------------------------------------------------------------------

<!-- ::: aside -->
<!-- ```{r} -->
<!-- CV %<>% print_text_block('wp_aside') -->
<!-- ``` -->
<!-- ::: -->

```{r}
CV %<>% print_section('working_papers')
```

<!-- These breaks just force a new page so section doesnt get cut off -->
<br>
<br>
<br>


Academic Publications {data-icon=book}
--------------------------------------------------------------------------------

<!-- ::: aside -->
<!-- ```{r} -->
<!-- CV %<>% print_text_block('publications_aside') -->
<!-- ``` -->
<!-- ::: -->

```{r}
CV %<>% print_section('academic_articles')
```

Industry Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('industy_experience_aside')
```
:::

```{r}
CV %<>% print_section('industry_positions')
```

<!-- Selected Data Science Writing {data-icon=chart-line} -->
<!-- -------------------------------------------------------------------------------- -->

<!-- ::: aside -->
<!-- ```{r} -->
<!-- CV %<>% print_text_block('data_science_writing_aside') -->
<!-- ``` -->
<!-- ::: -->

<!-- ```{r} -->
<!-- CV %<>% print_section('data_science_writings') -->
<!-- ``` -->



<!-- Selected Press (About)  {data-icon=newspaper} -->
<!-- -------------------------------------------------------------------------------- -->

<!-- ```{r} -->
<!-- CV %<>% print_section('about_me_press') -->
<!-- ``` -->


<!-- <br> -->
<!-- <br> -->


<!-- Selected Press (By)  {data-icon=newspaper} -->
<!-- -------------------------------------------------------------------------------- -->

<!-- ```{r} -->
<!-- CV %<>% print_section('by_me_press') -->
<!-- ``` -->





```{r}
CV %<>% print_links()
```

